// Code generated by manual patch. DO NOT EDIT.

package v1

import (
    runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *Hello) DeepCopyInto(out *Hello) {
    *out = *in
    out.TypeMeta = in.TypeMeta
    in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
    out.Spec = in.Spec
    out.Status = in.Status
}

func (in *Hello) DeepCopy() *Hello {
    if in == nil {
        return nil
    }
    out := new(Hello)
    in.DeepCopyInto(out)
    return out
}

func (in *Hello) DeepCopyObject() runtime.Object {
    if c := in.DeepCopy(); c != nil {
        return c
    }
    return nil
}

func (in *HelloList) DeepCopyInto(out *HelloList) {
    *out = *in
    out.TypeMeta = in.TypeMeta
    in.ListMeta.DeepCopyInto(&out.ListMeta)
    if in.Items != nil {
        out.Items = make([]Hello, len(in.Items))
        for i := range in.Items {
            in.Items[i].DeepCopyInto(&out.Items[i])
        }
    }
}

func (in *HelloList) DeepCopy() *HelloList {
    if in == nil {
        return nil
    }
    out := new(HelloList)
    in.DeepCopyInto(out)
    return out
}

func (in *HelloList) DeepCopyObject() runtime.Object {
    if c := in.DeepCopy(); c != nil {
        return c
    }
    return nil
}